services:
  app:
    container_name: projectflow-be
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - redis-docker-service
      - mongodb
    env_file: ".env.local"
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    networks:
      - mynetwork

  redis-docker-service:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - mynetwork

volumes:
  mongo-data:
networks:
  mynetwork:
